# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec03dbf74e97ff81ebff2e50d235cc845df6c78986f653cf843c07f7b039a2ec9a8bf816fd7cb16ab7b932ae7bf1a05558a9b3171ad55a83e5a6499d6ddec11

test:
  secret_key_base: 4be45b1c11e067e98532d683096725901f02532e2e7fadb82c07cb26490c363177f58953ac9a2458f46332a4910ccc1fe10fed3d59778cfe86d571ba1d7c1aac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
